sudo: required
language: generic


services:
  - docker

before_install:
  - docker build -t mouradvip7/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true  mouradvip7/react-test npm test -- --coverage

after_succes:
  - docker build -t mouradvip7/multi-client ./client
  - docker build -t mouradvip7/multi-nginx ./nginx
  - docker build -t mouradvip7/multi-server ./server
  - docker build -t mouradvip7/multi-worker ./worker

  #push images to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mouradvip7/multi-client
  - docker push mouradvip7/multi-nginx 
  - docker push mouradvip7/multi-server 
  - docker push mouradvip7/multi-worker
